addons:
  apt:
    packages:
      - lib32stdc++6

env:
  global:
    - FLUTTER_CHANNEL=stable

cache:
  cocoapods: true
  directories:
  - $HOME/.pub-cache

if: branch = main

install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get
  - gem install coveralls-lcov
script:
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --coverage --coverage-path=lcov.info
  - cd example && flutter build web --release && cd ..
  - flutter pub publish --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls-lcov lcov.info
before_deploy:
  - chmod +x ./.travis/publish.sh
  - mv ./.travis ../
deploy:
  - provider: surge
    skip_cleanup: true
    project: ./exmaple/build/web
    domain: flutter-adaptive-layout.surge.sh
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: '../.travis/publish.sh'
    on:
      tags: true
